services:
  backend:
    build:
      context: ./ws
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./ws/data:/app/data
      - ./ws/logs:/app/logs
      - ./ws/uploads:/app/uploads
      - ./ws/.env:/app/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend/.env:/app/.env
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
      
networks:
  app-network:
    driver: bridge
